require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-factory_bot
AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable
  Exclude:
    - .gems/**/*
    - bin/**/*
    - alfred/config/**/*
    - db/**/*
    - log/**/*
    - public/**/*
    - tmp/**/*
    - vendor/**/*
    - spec/rails_helper.rb
    - spec/spec_helper.rb
    - spec/acceptance_helper.rb
    - config.ru
    - Guardfile
    - Rakefile
    - alfred/apps/**/application.rb
    - lib/tasks/*.rake

Layout/TrailingEmptyLines:
  Enabled: true

Metrics/ClassLength:
  Enabled: false # re-enable in the future

Metrics/CyclomaticComplexity:
  Enabled: false # re-enable in the future

Layout/LineLength:
  Max: 130
  Exclude:
    - config/initializers/*.rb
    - spec/**/*

Metrics/MethodLength:
  Max: 25
  Exclude:
    - spec/**/*

Metrics/ModuleLength:
  Enabled: false # re-enable in the future

Metrics/BlockLength:
  Max: 30
  Exclude:
    - spec/**/*

Metrics/AbcSize:
  Max: 45
  AllowedMethods:
    - "call"
    - "perform"
  Exclude:
    - "spec/**/*"

Naming/VariableNumber:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/EachWithObject:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/BlockDelimiters:
  Enabled: true
  Exclude:
    - spec/**/*

Style/OpenStructUse:
  Enabled: true
  Exclude:
    - spec/**/*

Style/OptionalBooleanParameter:
  Enabled: true
  Exclude:
    - lib/workers/*

Layout/EmptyLines:
  Enabled: true

Layout/EmptyLinesAroundAccessModifier:
  Enabled: true

Layout/EmptyLinesAroundBlockBody:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/EmptyLinesAroundExceptionHandlingKeywords:
  Enabled: false

Layout/EmptyLinesAroundMethodBody:
  Enabled: false

Layout/EmptyLinesAroundModuleBody:
  Enabled: false

Layout/EmptyLineBetweenDefs:
  Enabled: true

Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods

Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Style/ClassAndModuleChildren:
  Enabled: false

Style/LambdaCall:
  EnforcedStyle: braces

Style/ModuleFunction:
  EnforcedStyle: extend_self

Style/NonNilCheck:
  IncludeSemanticChanges: true

Style/SingleLineMethods:
  Enabled: false

Style/RaiseArgs:
  EnforcedStyle: compact

Style/StructInheritance:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    default: ()
    "%r": "{}"
    "%i": "()"
    "%w": "()"
    "%I": "()"
    "%W": "()"

Rails/SkipsModelValidations:
  Enabled: false

Lint/RedundantSplatExpansion:
  Enabled: false

# find_by_something is manually written (not translatable to find_by(something: ))
Rails/DynamicFindBy:
  Enabled: false

Rails/HasManyOrHasOneDependent:
  Enabled: false

Rails/InverseOf:
  Enabled: false

Rails/HttpPositionalArguments:
  Exclude:
    - "spec/**/*" # This interferes with our helpers for token testing

Rails/UnknownEnv:
  Environments:
    - production
    - staging
    - development
    - test


RSpec/IndexedLet:
  Enabled: false
RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/MessageSpies:
  Enabled: false

RSpec/StubbedMock:
  Enabled: false # we usually try to use expect

RSpec/MultipleExpectations:
  Enabled: false # we want to reduce test initializations

RSpec/ExampleLength:
  Max: 50

RSpec/NamedSubject:
  Enabled: false

RSpec/ExpectInHook:
  Enabled: false # we sometimes use expect in before hooks to share expectations

RSpec/DescribeClass:
  Enabled: false # we sometimes have strings to describe the spec

RSpec/NestedGroups:
  Enabled: false

RSpec/ContextWording:
  Enabled: false # TODO: enable this and fix all the errors

RSpec/LetSetup:
  Enabled: false # TODO: enable this and fix all the errors

RSpec/VerifiedDoubles:
  Enabled: false # TODO: enable this and fix all the errors

RSpec/RepeatedExampleGroupDescription:
  Enabled: false # TODO: enable this and fix all the errors

RSpec/MultipleDescribes:
  Enabled: false # TODO: enable this and fix all the errors

RSpec/InstanceVariable:
  Enabled: false # TODO: enable this and fix all the errors

RSpec/MessageChain:
  Enabled: false # TODO: enable this and fix all the errors

RSpec/AnyInstance:
  Enabled: false # TODO: enable this and fix all the errors

RSpec/RepeatedExampleGroupBody:
  Enabled: false # TODO: enable this and fix all the errors

RSpec/EmptyExampleGroup:
  Exclude:
    - spec/acceptance/**/*

RSpec/FilePath:
  Enabled: false

FactoryBot/CreateList:
  Enabled: false
