{
  "openapi": "3.0.1",
  "info": {
    "title": "Nine Project API V1",
    "version": "v1",
    "description": "API documentation for Nine Project"
  },
  "components": {
    "securitySchemes": {
      "bearer_auth": {
        "type": "http",
        "scheme": "bearer",
        "bearerFormat": "JWT"
      }
    }
  },
  "paths": {
    "/brands": {
      "get": {
        "summary": "Lists all brands",
        "tags": [
          "Brands"
        ],
        "security": [
          {
            "bearer_auth": [

            ]
          }
        ],
        "responses": {
          "200": {
            "description": "brands found",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "properties": {
                      "id": {
                        "type": "integer"
                      },
                      "name": {
                        "type": "string"
                      },
                      "rate": {
                        "type": "decimal",
                        "format": "float"
                      },
                      "headquarters": {
                        "type": "string"
                      },
                      "industry": {
                        "type": "string"
                      },
                      "founder": {
                        "type": "string"
                      },
                      "website": {
                        "type": "string"
                      },
                      "status": {
                        "type": "string",
                        "enum": [
                          "active",
                          "inactive"
                        ]
                      }
                    },
                    "required": [
                      "name",
                      "rate",
                      "headquarters",
                      "industry",
                      "founder",
                      "website",
                      "status"
                    ]
                  }
                }
              }
            }
          },
          "401": {
            "description": "unauthorized",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "error": {
                      "type": "array"
                    }
                  }
                }
              }
            }
          }
        }
      },
      "post": {
        "summary": "Creates a brand",
        "tags": [
          "Brands"
        ],
        "security": [
          {
            "bearer_auth": [

            ]
          }
        ],
        "parameters": [

        ],
        "responses": {
          "201": {
            "description": "brand created",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "id": {
                      "type": "integer"
                    },
                    "name": {
                      "type": "string"
                    },
                    "rate": {
                      "type": "decimal",
                      "format": "float"
                    },
                    "headquarters": {
                      "type": "string"
                    },
                    "industry": {
                      "type": "string"
                    },
                    "founder": {
                      "type": "string"
                    },
                    "website": {
                      "type": "string"
                    },
                    "status": {
                      "type": "string",
                      "enum": [
                        "active",
                        "inactive"
                      ]
                    }
                  },
                  "required": [
                    "name",
                    "rate",
                    "headquarters",
                    "industry",
                    "founder",
                    "website",
                    "status"
                  ]
                }
              }
            }
          },
          "422": {
            "description": "invalid request",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "error": {
                      "type": "array"
                    }
                  }
                }
              }
            }
          }
        },
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "name": {
                    "type": "string"
                  },
                  "rate": {
                    "type": "decimal",
                    "minimum": 0
                  },
                  "headquarters": {
                    "type": "string"
                  },
                  "industry": {
                    "type": "string"
                  },
                  "founder": {
                    "type": "string"
                  },
                  "website": {
                    "type": "string"
                  },
                  "status": {
                    "type": "string",
                    "enum": [
                      "active",
                      "inactive"
                    ],
                    "default": "active"
                  }
                },
                "required": [
                  "name",
                  "rate",
                  "headquarters",
                  "industry",
                  "founder",
                  "website"
                ]
              }
            }
          }
        }
      }
    },
    "/brands/{id}": {
      "parameters": [
        {
          "name": "id",
          "in": "path",
          "required": true,
          "schema": {
            "type": "integer"
          }
        }
      ],
      "get": {
        "summary": "Retrieves a brand",
        "tags": [
          "Brands"
        ],
        "security": [
          {
            "bearer_auth": [

            ]
          }
        ],
        "responses": {
          "200": {
            "description": "brand found",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "id": {
                      "type": "integer"
                    },
                    "name": {
                      "type": "string"
                    },
                    "rate": {
                      "type": "decimal",
                      "format": "float"
                    },
                    "headquarters": {
                      "type": "string"
                    },
                    "industry": {
                      "type": "string"
                    },
                    "founder": {
                      "type": "string"
                    },
                    "website": {
                      "type": "string"
                    },
                    "status": {
                      "type": "string",
                      "enum": [
                        "active",
                        "inactive"
                      ]
                    }
                  },
                  "required": [
                    "name",
                    "rate",
                    "headquarters",
                    "industry",
                    "founder",
                    "website",
                    "status"
                  ]
                }
              }
            }
          },
          "404": {
            "description": "brand not found",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "error": {
                      "type": "array"
                    }
                  }
                }
              }
            }
          }
        }
      },
      "patch": {
        "summary": "Updates brand status",
        "tags": [
          "Brands"
        ],
        "security": [
          {
            "bearer_auth": [

            ]
          }
        ],
        "parameters": [

        ],
        "responses": {
          "201": {
            "description": "brand status updated"
          },
          "404": {
            "description": "brand not found",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "error": {
                      "type": "array"
                    }
                  }
                }
              }
            }
          }
        },
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "status": {
                    "type": "string",
                    "enum": [
                      "active",
                      "inactive"
                    ]
                  }
                }
              }
            }
          }
        }
      },
      "delete": {
        "summary": "Deletes a brand",
        "tags": [
          "Brands"
        ],
        "security": [
          {
            "bearer_auth": [

            ]
          }
        ],
        "responses": {
          "200": {
            "description": "brand deleted"
          },
          "404": {
            "description": "brand not found",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "error": {
                      "type": "array"
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "unauthorized",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "error": {
                      "type": "array"
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  },
  "servers": [
    {
      "url": "{protocol}://{defaultHost}",
      "variables": {
        "protocol": {
          "default": "http"
        },
        "defaultHost": {
          "default": "localhost:3000"
        }
      }
    }
  ]
}